# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7693df0a8e0871111864908f0d52f8daf419883709b74d03c820a4f26178c5ebef33410cba3a5fd6d2e0ac7ad7b33664cbb0d2af18d4ae0eff3a064ec29fdf77

test:
  secret_key_base: f36cdb7d45d36e249c31a005a44f7157aabeaa1e9082117717165d78d2451afdf4c9833a799500c1205f82fb796c4f62e635cb608d11a9d48f4e8ac59e044a7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
